import 'package:flutter/material.dart';

const green = Color(0xFF2E7D32);
const darkGreen = Color(0xFF1B5E20);
const paleGreen = Color(0xFFE8F5E9);
const background = Color(0xFFF5F8F4);

enum AppModule { dashboard, sites, customers, orders, employees, time, calendar, reports, materials, machines, tasks }

class Entry { String title; String details; String status; Entry(this.title, this.details, {this.status='Neu'}); }

class PincusApp extends StatefulWidget { const PincusApp({super.key}); @override State<PincusApp> createState()=>_PincusAppState(); }
class _PincusAppState extends State<PincusApp> {
  AppModule current=AppModule.dashboard;
  final Map<AppModule,List<Entry>> data={for(final m in AppModule.values) m:[]};
  String label(AppModule m){switch(m){case AppModule.dashboard:return'Dashboard';case AppModule.sites:return'Baustellen';case AppModule.customers:return'Kunden';case AppModule.orders:return'Aufträge';case AppModule.employees:return'Mitarbeiter';case AppModule.time:return'Zeiterfassung';case AppModule.calendar:return'Kalender';case AppModule.reports:return'Berichte';case AppModule.materials:return'Material';case AppModule.machines:return'Maschinen';case AppModule.tasks:return'Aufgaben';}}
  IconData ico(AppModule m){switch(m){case AppModule.dashboard:return Icons.dashboard_outlined;case AppModule.sites:return Icons.location_on_outlined;case AppModule.customers:return Icons.people_outline;case AppModule.orders:return Icons.assignment_outlined;case AppModule.employees:return Icons.groups_outlined;case AppModule.time:return Icons.schedule_outlined;case AppModule.calendar:return Icons.calendar_month_outlined;case AppModule.reports:return Icons.description_outlined;case AppModule.materials:return Icons.inventory_2_outlined;case AppModule.machines:return Icons.construction_outlined;case AppModule.tasks:return Icons.checklist_outlined;}}
  @override Widget build(BuildContext context){final mobile=MediaQuery.sizeOf(context).width<800;return Scaffold(backgroundColor:background,appBar:AppBar(backgroundColor:green,foregroundColor:Colors.white,title:Row(children:[const Icon(Icons.park_outlined),const SizedBox(width:10),Text(label(current),style:const TextStyle(fontWeight:FontWeight.w700))]),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none))]),body:Row(children:[if(!mobile)Sidebar(selected:current,onSelect:(m)=>setState(()=>current=m)),Expanded(child:current==AppModule.dashboard?Dashboard(data:data,open:(m)=>setState(()=>current=m)):ModulePage(module:current,items:data[current]!,icon:ico(current),onAdd:(e)=>setState(()=>data[current]!.add(e)),onDelete:(e)=>setState(()=>data[current]!.remove(e)),label:label(current)))]),bottomNavigationBar:mobile?NavigationBar(selectedIndex:current==AppModule.sites?1:current==AppModule.customers?2:current==AppModule.time?3:0,onDestinationSelected:(i)=>setState(()=>current=i==1?AppModule.sites:i==2?AppModule.customers:i==3?AppModule.time:AppModule.dashboard),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Start'),NavigationDestination(icon:Icon(Icons.location_on_outlined),label:'Baustellen'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Kunden'),NavigationDestination(icon:Icon(Icons.schedule_outlined),label:'Zeit')]):null);}
}

class Sidebar extends StatelessWidget{final AppModule selected;final ValueChanged<AppModule> onSelect;const Sidebar({super.key,required this.selected,required this.onSelect});@override Widget build(BuildContext context){return Container(width:118,color:Colors.white,child:Column(children:[Padding(padding:const EdgeInsets.all(9),child:Image.asset('assets/images/logo.png',height:54,errorBuilder:(_,__,___)=>const Icon(Icons.park,color:green,size:42))),Expanded(child:ListView(children:AppModule.values.map((m)=>InkWell(onTap:()=>onSelect(m),child:Container(margin:const EdgeInsets.symmetric(horizontal:6,vertical:2),padding:const EdgeInsets.symmetric(vertical:8),decoration:BoxDecoration(color:selected==m?paleGreen:Colors.transparent,borderRadius:BorderRadius.circular(14)),child:Column(children:[Icon(_icon(m),size:26,color:selected==m?green:Colors.black54),const SizedBox(height:3),Text(_label(m),textAlign:TextAlign.center,style:TextStyle(fontSize:11.5,fontWeight:selected==m?FontWeight.w700:FontWeight.w500))])))).toList()))]));}}
String _label(AppModule m){switch(m){case AppModule.dashboard:return'Dashboard';case AppModule.sites:return'Baustellen';case AppModule.customers:return'Kunden';case AppModule.orders:return'Aufträge';case AppModule.employees:return'Mitarbeiter';case AppModule.time:return'Zeiterfassung';case AppModule.calendar:return'Kalender';case AppModule.reports:return'Berichte';case AppModule.materials:return'Material';case AppModule.machines:return'Maschinen';case AppModule.tasks:return'Aufgaben';}}
IconData _icon(AppModule m){switch(m){case AppModule.dashboard:return Icons.dashboard_outlined;case AppModule.sites:return Icons.location_on_outlined;case AppModule.customers:return Icons.people_outline;case AppModule.orders:return Icons.assignment_outlined;case AppModule.employees:return Icons.groups_outlined;case AppModule.time:return Icons.schedule_outlined;case AppModule.calendar:return Icons.calendar_month_outlined;case AppModule.reports:return Icons.description_outlined;case AppModule.materials:return Icons.inventory_2_outlined;case AppModule.machines:return Icons.construction_outlined;case AppModule.tasks:return Icons.checklist_outlined;}}

class Dashboard extends StatelessWidget{final Map<AppModule,List<Entry>> data;final ValueChanged<AppModule> open;const Dashboard({super.key,required this.data,required this.open});@override Widget build(BuildContext context){return ListView(padding:const EdgeInsets.fromLTRB(30,42,30,50),children:[const Text('Pincus Baum und Landschaftspflege',style:TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:darkGreen)),const SizedBox(height:4),const Text('Baustellenmanagement & Unternehmensverwaltung',style:TextStyle(fontSize:17,color:Colors.black54)),const SizedBox(height:28),Wrap(spacing:14,runSpacing:14,children:[card('Baustellen',AppModule.sites,Icons.location_on),card('Kunden',AppModule.customers,Icons.people),card('Aufträge',AppModule.orders,Icons.assignment),card('Mitarbeiter',AppModule.employees,Icons.groups)]),const SizedBox(height:24),Card(child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[const Icon(Icons.account_tree_outlined,color:green,size:30),const SizedBox(width:14),const Expanded(child:Text('Kunde → Baustelle → Auftrag → Mitarbeiter → Arbeitszeit',style:TextStyle(fontWeight:FontWeight.w600))),FilledButton(onPressed:()=>open(AppModule.orders),child:const Text('Auftrag anlegen'))])))];}Widget card(String n,AppModule m,IconData i)=>SizedBox(width:300,child:Card(child:InkWell(onTap:()=>open(m),child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:paleGreen,borderRadius:BorderRadius.circular(14)),child:Icon(i,color:green)),const SizedBox(width:15),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(fontWeight:FontWeight.w700)),Text('${data[m]!.length}',style:const TextStyle(fontSize:27,fontWeight:FontWeight.w800,color:darkGreen)),const Text('Im System',style:TextStyle(color:Colors.black54))])])))));}}

class ModulePage extends StatefulWidget{final AppModule module;final List<Entry> items;final IconData icon;final String label;final ValueChanged<Entry> onAdd;final ValueChanged<Entry> onDelete;const ModulePage({super.key,required this.module,required this.items,required this.icon,required this.label,required this.onAdd,required this.onDelete});@override State<ModulePage> createState()=>_ModulePageState();}
class _ModulePageState extends State<ModulePage>{String search='';@override Widget build(BuildContext context){final list=widget.items.where((e)=>('${e.title} ${e.details} ${e.status}').toLowerCase().contains(search.toLowerCase())).toList();return ListView(padding:const EdgeInsets.fromLTRB(30,26,30,40),children:[Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:paleGreen,borderRadius:BorderRadius.circular(14)),child:Icon(widget.icon,color:green)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.label,style:const TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:darkGreen)),const Text('Einträge verwalten',style:TextStyle(color:Colors.black54))])),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('Neu'))]),const SizedBox(height:18),TextField(onChanged:(v)=>setState(()=>search=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'${widget.label} durchsuchen …',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none))),const SizedBox(height:12),Text('${list.length} Einträge',style:const TextStyle(fontWeight:FontWeight.w700,color:darkGreen)),const SizedBox(height:8),...list.map((e)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:paleGreen,child:Icon(widget.icon,color:green)),title:Text(e.title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(e.details),trailing:Wrap(children:[IconButton(onPressed:()=>edit(e),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>widget.onDelete(e),icon:const Icon(Icons.delete_outline))]))))]);}
Future<void> add()=>showDialog<Entry>(context:context,builder:(_)=>EntryDialog(label:widget.label)).then((e){if(e!=null)widget.onAdd(e);});
Future<void> edit(Entry e)=>showDialog<Entry>(context:context,builder:(_)=>EntryDialog(label:widget.label,item:e)).then((n){if(n!=null){e.title=n.title;e.details=n.details;e.status=n.status;setState((){});}});
}

class EntryDialog extends StatefulWidget{final String label;final Entry? item;const EntryDialog({super.key,required this.label,this.item});@override State<EntryDialog> createState()=>_EntryDialogState();}
class _EntryDialogState extends State<EntryDialog>{late TextEditingController title;late TextEditingController details;String status='Neu';@override void initState(){super.initState();title=TextEditingController(text:widget.item?.title??'');details=TextEditingController(text:widget.item?.details??'');status=widget.item?.status??'Neu';}@override void dispose(){title.dispose();details.dispose();super.dispose();}@override Widget build(BuildContext context){return AlertDialog(title:Text('${widget.item==null?'Neu':'Bearbeiten'} – ${widget.label}'),content:SizedBox(width:560,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Bezeichnung',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:details,maxLines:4,decoration:const InputDecoration(labelText:'Details / Notizen',border:OutlineInputBorder())),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:status,decoration:const InputDecoration(labelText:'Status',border:OutlineInputBorder()),items:const['Neu','In Arbeit','Erledigt','Wichtig'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x){if(x!=null)setState(()=>status=x);})])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Abbrechen')),FilledButton(onPressed:(){if(title.text.trim().isEmpty)return;Navigator.pop(context,Entry(title.text.trim(),details.text.trim(),status:status));},child:const Text('Speichern'))]);}}
