import 'package:drift/drift.dart' show Value;
import 'package:flutter/material.dart';
import 'core/database/app_database.dart';

const kGreen = Color(0xFF2E7D32);
const kDarkGreen = Color(0xFF1B5E20);
const kPaleGreen = Color(0xFFE8F5E9);
const kBg = Color(0xFFF6F8F5);

enum WorkModule { sites, customers, orders, employees, time, calendar, reports, materials, machines, tasks }

class PincusWorkspace extends StatefulWidget {
  const PincusWorkspace({super.key});
  @override State<PincusWorkspace> createState() => _PincusWorkspaceState();
}

class _PincusWorkspaceState extends State<PincusWorkspace> {
  final db = AppDatabase();
  WorkModule module = WorkModule.sites;
  @override void dispose(){db.close();super.dispose();}
  @override Widget build(BuildContext context){
    final mobile=MediaQuery.sizeOf(context).width<800;
    return Scaffold(
      appBar: AppBar(backgroundColor:kGreen,foregroundColor:Colors.white,title:Row(children:[const Icon(Icons.park_outlined),const SizedBox(width:10),Text(title(module),style:const TextStyle(fontWeight:FontWeight.w700))]),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none)),const SizedBox(width:8)]),
      body:Row(children:[if(!mobile)WorkSidebar(selected:module,onSelect:(m)=>setState(()=>module=m)),Expanded(child:module==WorkModule.calendar?const CalendarView():module==WorkModule.sites?ModuleView(db:db,kind:module):ModuleView(db:db,kind:module))]),
      bottomNavigationBar:mobile?NavigationBar(selectedIndex:_mobileIndex(module),onDestinationSelected:(i)=>setState(()=>module=_mobileModule(i)),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Start'),NavigationDestination(icon:Icon(Icons.location_on_outlined),label:'Baustellen'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Kunden'),NavigationDestination(icon:Icon(Icons.schedule_outlined),label:'Zeit'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'Mehr')]):null,
    );
  }
  int _mobileIndex(WorkModule m)=>switch(m){WorkModule.sites=>1,WorkModule.customers=>2,WorkModule.time=>3,_=>0};
  WorkModule _mobileModule(int i)=>switch(i){1=>WorkModule.sites,2=>WorkModule.customers,3=>WorkModule.time,_=>WorkModule.sites};
}

class WorkSidebar extends StatelessWidget{
  final WorkModule selected;final ValueChanged<WorkModule> onSelect;
  const WorkSidebar({super.key,required this.selected,required this.onSelect});
  static const entries=<WorkModule>[WorkModule.sites,WorkModule.customers,WorkModule.orders,WorkModule.employees,WorkModule.time,WorkModule.calendar,WorkModule.reports,WorkModule.materials,WorkModule.machines,WorkModule.tasks];
  @override Widget build(BuildContext context)=>Container(width:112,color:Colors.white,child:Column(children:[Padding(padding:const EdgeInsets.all(9),child:Image.asset('assets/images/logo.png',height:54)),Expanded(child:ListView(children:entries.map((m)=>Padding(padding:const EdgeInsets.symmetric(horizontal:6,vertical:2),child:InkWell(borderRadius:BorderRadius.circular(14),onTap:()=>onSelect(m),child:Container(padding:const EdgeInsets.symmetric(vertical:8),decoration:BoxDecoration(color:selected==m?kPaleGreen:Colors.transparent,borderRadius:BorderRadius.circular(14)),child:Column(children:[Icon(icon(m),color:selected==m?kGreen:Colors.black54,size:27),const SizedBox(height:3),Text(title(m),textAlign:TextAlign.center,style:TextStyle(fontSize:12,fontWeight:selected==m?FontWeight.w700:FontWeight.w500,color:selected==m?kDarkGreen:Colors.black87))]))))).toList()))]));
}

String title(WorkModule m)=>switch(m){WorkModule.sites=>'Baustellen',WorkModule.customers=>'Kunden',WorkModule.orders=>'Aufträge',WorkModule.employees=>'Mitarbeiter',WorkModule.time=>'Zeiterfassung',WorkModule.calendar=>'Kalender',WorkModule.reports=>'Berichte',WorkModule.materials=>'Material',WorkModule.machines=>'Maschinen',WorkModule.tasks=>'Aufgaben'};
IconData icon(WorkModule m)=>switch(m){WorkModule.sites=>Icons.location_on,WorkModule.customers=>Icons.people,WorkModule.orders=>Icons.assignment,WorkModule.employees=>Icons.groups,WorkModule.time=>Icons.schedule,WorkModule.calendar=>Icons.calendar_month,WorkModule.reports=>Icons.description,WorkModule.materials=>Icons.inventory_2,WorkModule.machines=>Icons.construction,WorkModule.tasks=>Icons.checklist};

class ModuleView extends StatefulWidget{final AppDatabase db;final WorkModule kind;const ModuleView({super.key,required this.db,required this.kind});@override State<ModuleView> createState()=>_ModuleViewState();}
class _ModuleViewState extends State<ModuleView>{late Future<List<dynamic>> future;String search='';@override void initState(){super.initState();reload();}void reload()=>future=query();Future<List<dynamic>> query()async=>switch(widget.kind){WorkModule.sites:widget.db.select(widget.db.sites).get(),WorkModule.customers:widget.db.select(widget.db.customers).get(),WorkModule.orders:widget.db.select(widget.db.orders).get(),WorkModule.employees:widget.db.select(widget.db.employees).get(),WorkModule.time:widget.db.select(widget.db.timeEntries).get(),WorkModule.reports:widget.db.select(widget.db.reports).get(),WorkModule.materials:widget.db.select(widget.db.materialsTable).get(),WorkModule.machines:widget.db.select(widget.db.machinesTable).get(),WorkModule.tasks:widget.db.select(widget.db.tasksTable).get(),WorkModule.calendar:Future.value([])};
String primary(dynamic x)=>switch(widget.kind){WorkModule.sites=>x.title,WorkModule.customers=>x.name,WorkModule.orders=>x.title,WorkModule.employees=>x.name,WorkModule.time=>x.employeeName,WorkModule.reports=>x.title,WorkModule.materials=>x.name,WorkModule.machines=>x.name,WorkModule.tasks=>x.title,WorkModule.calendar=>''};
String secondary(dynamic x)=>switch(widget.kind){WorkModule.sites=>x.address,WorkModule.customers=>[x.contact,x.phone,x.address].where((v)=>v.toString().isNotEmpty).join(' • '),WorkModule.orders=>'${x.status} • ${x.date} • ${x.price.toStringAsFixed(2)} €',WorkModule.employees=>'${x.role} • ${x.targetHours.toStringAsFixed(1)} h/Woche',WorkModule.time=>'${_fmtDate(x.date)} • ${_fmtTime(x.startTime)}',WorkModule.reports=>'${x.date} • ${x.content}',WorkModule.materials=>'${x.stock} ${x.unit} • ${x.category??''}',WorkModule.machines=>'${x.status} • ${x.operatingHours} h',WorkModule.tasks=>'${x.status} • ${x.priority} • ${x.category}',WorkModule.calendar=>''};
@override Widget build(BuildContext context)=>Stack(children:[const Watermark(),FutureBuilder<List<dynamic>>(future:future,builder:(context,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator(color:kGreen));if(s.hasError)return Center(child:Text('Fehler: ${s.error}'));final all=s.data??[];final items=all.where((x)=>('${primary(x)} ${secondary(x)}').toLowerCase().contains(search.toLowerCase())).toList();return ListView(padding:const EdgeInsets.fromLTRB(30,26,30,40),children:[Row(children:[Container(width:54,height:54,decoration:BoxDecoration(color:kPaleGreen,borderRadius:BorderRadius.circular(14)),child:Icon(icon(widget.kind),color:kGreen,size:29)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title(widget.kind),style:const TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:kDarkGreen)),const Text('Verwalten, suchen und bearbeiten',style:TextStyle(color:Colors.black54))])),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:kGreen),onPressed:()=>open(),icon:const Icon(Icons.add),label:const Text('Neu'))]),const SizedBox(height:18),TextField(onChanged:(v)=>setState(()=>search=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'${title(widget.kind)} durchsuchen …',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none))),const SizedBox(height:12),Text('${items.length} Einträge',style:const TextStyle(fontWeight:FontWeight.w700,color:kDarkGreen)),const SizedBox(height:8),if(items.isEmpty)Card(child:Padding(padding:const EdgeInsets.all(36),child:Column(children:[Icon(icon(widget.kind),size:50,color:Colors.black26),const SizedBox(height:10),Text(search.isEmpty?'Noch keine Einträge vorhanden.':'Keine passenden Einträge gefunden.'),if(search.isEmpty)Padding(padding:const EdgeInsets.only(top:12),child:OutlinedButton.icon(onPressed:()=>open(),icon:const Icon(Icons.add),label:const Text('Eintrag anlegen')))]))) else ...items.map((x)=>Card(margin:const EdgeInsets.only(bottom:9),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:18,vertical:5),leading:CircleAvatar(backgroundColor:kPaleGreen,child:Icon(icon(widget.kind),color:kGreen)),title:Text(primary(x),style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(secondary(x),maxLines:2,overflow:TextOverflow.ellipsis),trailing:Wrap(children:[IconButton(tooltip:'Bearbeiten',onPressed:()=>open(x),icon:const Icon(Icons.edit_outlined)),IconButton(tooltip:'Löschen',onPressed:()=>remove(x),icon:const Icon(Icons.delete_outline))]),onTap:()=>open(x))))]);})]);
Future<void> open([dynamic item])async{final v=await showDialog<Map<String,String>>(context:context,builder:(_)=>Editor(db:widget.db,kind:widget.kind,item:item));if(v==null)return;try{if(item==null)await insert(v);else await update(item,v);setState(reload);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Eintrag gespeichert.'),backgroundColor:kGreen));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Fehler beim Speichern: $e'),backgroundColor:Colors.red));}}
Future<void> remove(dynamic x)async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Eintrag löschen?'),content:Text('„${primary(x)}“ wird entfernt.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Abbrechen')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Löschen'))]));if(ok!=true)return;switch(widget.kind){case WorkModule.sites:await(widget.db.delete(widget.db.sites)..where((t)=>t.id.equals(x.id))).go();case WorkModule.customers:await(widget.db.delete(widget.db.customers)..where((t)=>t.id.equals(x.id))).go();case WorkModule.orders:await(widget.db.delete(widget.db.orders)..where((t)=>t.id.equals(x.id))).go();case WorkModule.employees:await(widget.db.delete(widget.db.employees)..where((t)=>t.id.equals(x.id))).go();case WorkModule.time:await(widget.db.delete(widget.db.timeEntries)..where((t)=>t.id.equals(x.id))).go();case WorkModule.reports:await(widget.db.delete(widget.db.reports)..where((t)=>t.id.equals(x.id))).go();case WorkModule.materials:await(widget.db.delete(widget.db.materialsTable)..where((t)=>t.id.equals(x.id))).go();case WorkModule.machines:await(widget.db.delete(widget.db.machinesTable)..where((t)=>t.id.equals(x.id))).go();case WorkModule.tasks:await(widget.db.delete(widget.db.tasksTable)..where((t)=>t.id.equals(x.id))).go();case WorkModule.calendar:break;}setState(reload);}
Future<void> insert(Map<String,String>v)async{switch(widget.kind){case WorkModule.sites:await widget.db.into(widget.db.sites).insert(SitesCompanion.insert(title:v['title']!,address:v['address']!,customerId:_st(v['customerId'])));case WorkModule.customers:await widget.db.into(widget.db.customers).insert(CustomersCompanion.insert(id:_id(),name:v['name']!,contact:Value(v['contact']??''),phone:Value(v['phone']??''),address:Value(v['address']??'')));case WorkModule.orders:await widget.db.into(widget.db.orders).insert(OrdersCompanion.insert(id:_id(),title:v['title']!,customerId:_st(v['customerId']),siteId:_it(v['siteId']),status:Value(v['status']??'Neu'),date:v['date']!,price:Value(_num(v['price']))));case WorkModule.employees:await widget.db.into(widget.db.employees).insert(EmployeesCompanion.insert(id:_id(),name:v['name']!,role:v['role']!,targetHours:Value(_num(v['targetHours']))));case WorkModule.time:await widget.db.into(widget.db.timeEntries).insert(TimeEntriesCompanion.insert(siteId:int.parse(v['siteId']!),employeeName:v['employeeName']!,date:_date(v['date']!),startTime:_dt(v['date']!,v['startTime']!),endTime:Value((v['endTime']??'').isEmpty?null:_dt(v['date']!,v['endTime']!)),breakMinutes:Value(_num(v['breakMinutes'])),notes:Value(_null(v['notes']))));case WorkModule.reports:await widget.db.into(widget.db.reports).insert(ReportsCompanion.insert(id:_id(),siteId:_it(v['siteId']),title:v['title']!,date:v['date']!,content:v['content']??''));case WorkModule.materials:await widget.db.into(widget.db.materialsTable).insert(MaterialsTableCompanion.insert(name:v['name']!,articleNumber:Value(_null(v['articleNumber'])),category:Value(_null(v['category'])),unit:Value(v['unit']??'Stk'),stock:Value(_num(v['stock'])),minimumStock:Value(_num(v['minimumStock'])),location:Value(_null(v['location'])),unitPrice:Value(_dbl(v['unitPrice'])),notes:Value(_null(v['notes']))));case WorkModule.machines:await widget.db.into(widget.db.machinesTable).insert(MachinesTableCompanion.insert(name:v['name']!,serialNumber:Value(_null(v['serialNumber'])),operatingHours:Value(_num(v['operatingHours'])),status:Value(v['status']??'bereit'),notes:Value(_null(v['notes']))));case WorkModule.tasks:await widget.db.into(widget.db.tasksTable).insert(TasksTableCompanion.insert(title:v['title']!,description:Value(_null(v['description'])),siteId:_it(v['siteId']),category:v['category']!,priority:Value(v['priority']??'normal'),status:Value(v['status']??'offen'),dueDate:Value((v['dueDate']??'').isEmpty?null:_date(v['dueDate']!)));case WorkModule.calendar:break;}}
Future<void> update(dynamic x,Map<String,String>v)async{switch(widget.kind){case WorkModule.sites:await(widget.db.update(widget.db.sites)..where((t)=>t.id.equals(x.id))).write(SitesCompanion(title:Value(v['title']!),address:Value(v['address']!),customerId:_st(v['customerId'])));case WorkModule.customers:await(widget.db.update(widget.db.customers)..where((t)=>t.id.equals(x.id))).write(CustomersCompanion(name:Value(v['name']!),contact:Value(v['contact']??''),phone:Value(v['phone']??''),address:Value(v['address']??'')));case WorkModule.orders:await(widget.db.update(widget.db.orders)..where((t)=>t.id.equals(x.id))).write(OrdersCompanion(title:Value(v['title']!),customerId:_st(v['customerId']),siteId:_it(v['siteId']),status:Value(v['status']??'Neu'),date:Value(v['date']!),price:Value(_num(v['price']))));case WorkModule.employees:await(widget.db.update(widget.db.employees)..where((t)=>t.id.equals(x.id))).write(EmployeesCompanion(name:Value(v['name']!),role:Value(v['role']!),targetHours:Value(_num(v['targetHours']))));case WorkModule.time:await(widget.db.update(widget.db.timeEntries)..where((t)=>t.id.equals(x.id))).write(TimeEntriesCompanion(siteId:Value(int.parse(v['siteId']!)),employeeName:Value(v['employeeName']!),date:Value(_date(v['date']!)),startTime:Value(_dt(v['date']!,v['startTime']!)),endTime:Value((v['endTime']??'').isEmpty?null:_dt(v['date']!,v['endTime']!)),breakMinutes:Value(_num(v['breakMinutes'])),notes:Value(_null(v['notes']))));case WorkModule.reports:await(widget.db.update(widget.db.reports)..where((t)=>t.id.equals(x.id))).write(ReportsCompanion(title:Value(v['title']!),siteId:_it(v['siteId']),date:Value(v['date']!),content:Value(v['content']??'')));case WorkModule.materials:await(widget.db.update(widget.db.materialsTable)..where((t)=>t.id.equals(x.id))).write(MaterialsTableCompanion(name:Value(v['name']!),articleNumber:Value(_null(v['articleNumber'])),category:Value(_null(v['category'])),unit:Value(v['unit']??'Stk'),stock:Value(_num(v['stock'])),minimumStock:Value(_num(v['minimumStock'])),location:Value(_null(v['location'])),unitPrice:Value(_dbl(v['unitPrice'])),notes:Value(_null(v['notes'])),updatedAt:Value(DateTime.now())));case WorkModule.machines:await(widget.db.update(widget.db.machinesTable)..where((t)=>t.id.equals(x.id))).write(MachinesTableCompanion(name:Value(v['name']!),serialNumber:Value(_null(v['serialNumber'])),operatingHours:Value(_num(v['operatingHours'])),status:Value(v['status']??'bereit'),notes:Value(_null(v['notes']))));case WorkModule.tasks:await(widget.db.update(widget.db.tasksTable)..where((t)=>t.id.equals(x.id))).write(TasksCompanion(title:Value(v['title']!),description:Value(_null(v['description'])),siteId:_it(v['siteId']),category:Value(v['category']!),priority:Value(v['priority']??'normal'),status:Value(v['status']??'offen'),dueDate:Value((v['dueDate']??'').isEmpty?null:_date(v['dueDate']!)));case WorkModule.calendar:break;}}
}

class Editor extends StatefulWidget{final AppDatabase db;final WorkModule kind;final dynamic item;const Editor({super.key,required this.db,required this.kind,this.item});@override State<Editor> createState()=>_EditorState();}
class _EditorState extends State<Editor>{final form=GlobalKey<FormState>();final c=<String,TextEditingController>{};List<Customer> customers=[];List<Site> sites=[];List<Employee> employees=[];bool loading=true;@override void initState(){super.initState();init();}
Future<void> init()async{await Future.wait([widget.db.select(widget.db.customers).get().then((v)=>customers=v),widget.db.select(widget.db.sites).get().then((v)=>sites=v),widget.db.select(widget.db.employees).get().then((v)=>employees=v)]);final x=widget.item;final m=<String,String>{};if(x!=null){switch(widget.kind){case WorkModule.sites:m.addAll({'title':x.title,'address':x.address,'customerId':x.customerId??''});case WorkModule.customers:m.addAll({'name':x.name,'contact':x.contact,'phone':x.phone,'address':x.address});case WorkModule.orders:m.addAll({'title':x.title,'customerId':x.customerId??'','siteId':x.siteId?.toString()??'','status':x.status,'date':x.date,'price':x.price.toString()});case WorkModule.employees:m.addAll({'name':x.name,'role':x.role,'targetHours':x.targetHours.toString()});case WorkModule.time:m.addAll({'employeeName':x.employeeName,'siteId':x.siteId.toString(),'date':_fmtDate(x.date),'startTime':_fmtTime(x.startTime),'endTime':x.endTime==null?'':_fmtTime(x.endTime!),'breakMinutes':x.breakMinutes.toString(),'notes':x.notes??''});case WorkModule.reports:m.addAll({'title':x.title,'siteId':x.siteId?.toString()??'','date':x.date,'content':x.content});case WorkModule.materials:m.addAll({'name':x.name,'articleNumber':x.articleNumber??'','category':x.category??'','unit':x.unit,'stock':x.stock.toString(),'minimumStock':x.minimumStock.toString(),'location':x.location??'','unitPrice':x.unitPrice?.toString()??'','notes':x.notes??''});case WorkModule.machines:m.addAll({'name':x.name,'serialNumber':x.serialNumber??'','operatingHours':x.operatingHours.toString(),'status':x.status,'notes':x.notes??''});case WorkModule.tasks:m.addAll({'title':x.title,'description':x.description??'','siteId':x.siteId?.toString()??'','category':x.category,'priority':x.priority,'status':x.status,'dueDate':x.dueDate==null?'':_fmtDate(x.dueDate!)});case WorkModule.calendar:break;}}for(final f in defs){c[f.key]=TextEditingController(text:m[f.key]??f.initial??'');}if(mounted)setState(()=>loading=false);}
List<Def> get defs=>switch(widget.kind){WorkModule.sites:[Def('title','Bezeichnung',required:true),Def('address','Adresse',required:true),Def('customerId','Kunde')],WorkModule.customers:[Def('name','Name / Firma',required:true),Def('contact','Ansprechpartner'),Def('phone','Telefon'),Def('address','Adresse')],WorkModule.orders:[Def('title','Auftragsbezeichnung',required:true),Def('customerId','Kunde'),Def('siteId','Baustelle'),Def('status','Status',initial:'Neu'),Def('date','Termin',date:true,required:true),Def('price','Preis',number:true)],WorkModule.employees:[Def('name','Name',required:true),Def('role','Rolle / Tätigkeit',required:true),Def('targetHours','Sollstunden / Woche',number:true,initial:'40')],WorkModule.time:[Def('employeeName','Mitarbeiter'),Def('siteId','Baustelle',required:true),Def('date','Datum',date:true,required:true),Def('startTime','Beginn',time:true,required:true),Def('endTime','Ende',time:true),Def('breakMinutes','Pause in Minuten',number:true,initial:'0'),Def('notes','Notizen',multi:true)],WorkModule.reports:[Def('title','Titel',required:true),Def('siteId','Baustelle'),Def('date','Datum',date:true,required:true),Def('content','Bericht / Inhalt',multi:true)],WorkModule.materials:[Def('name','Material / Artikel',required:true),Def('articleNumber','Artikelnummer'),Def('category','Kategorie'),Def('unit','Einheit',initial:'Stk'),Def('stock','Bestand',number:true,initial:'0'),Def('minimumStock','Mindestbestand',number:true,initial:'0'),Def('location','Lagerort'),Def('unitPrice','Einzelpreis',number:true),Def('notes','Notizen',multi:true)],WorkModule.machines:[Def('name','Maschine',required:true),Def('serialNumber','Seriennummer'),Def('operatingHours','Betriebsstunden',number:true,initial:'0'),Def('status','Status',initial:'bereit'),Def('notes','Notizen',multi:true)],WorkModule.tasks:[Def('title','Aufgabe',required:true),Def('description','Beschreibung',multi:true),Def('siteId','Baustelle'),Def('category','Kategorie',required:true,initial:'Allgemein'),Def('priority','Priorität',initial:'normal'),Def('status','Status',initial:'offen'),Def('dueDate','Fällig am',date:true)],WorkModule.calendar:[]};
Widget field(Def f){final isCustomer=f.key=='customerId';final isSite=f.key=='siteId';final isEmployee=f.key=='employeeName';if(isCustomer)return DropdownButtonFormField<String>(value:c[f.key]?.text.isEmpty??true?null:c[f.key]!.text,decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder(),filled:true,fillColor:Colors.white),items:customers.map((x)=>DropdownMenuItem(value:x.id,child:Text(x.name))).toList(),onChanged:(v)=>c[f.key]!.text=v??'',validator:f.required?(v)=>v==null||v.isEmpty?'Pflichtfeld':null:null);if(isSite)return DropdownButtonFormField<String>(value:c[f.key]?.text.isEmpty??true?null:c[f.key]!.text,decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder(),filled:true,fillColor:Colors.white),items:sites.map((x)=>DropdownMenuItem(value:x.id.toString(),child:Text('${x.title} — ${x.address}'))).toList(),onChanged:(v)=>c[f.key]!.text=v??'',validator:f.required?(v)=>v==null||v.isEmpty?'Baustelle auswählen':null:null);if(isEmployee)return DropdownButtonFormField<String>(value:c[f.key]?.text.isEmpty??true?null:c[f.key]!.text,decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder(),filled:true,fillColor:Colors.white),items:employees.map((x)=>DropdownMenuItem(value:x.name,child:Text('${x.name} — ${x.role}'))).toList(),onChanged:(v)=>c[f.key]!.text=v??'',validator:f.required?(v)=>v==null||v.isEmpty?'Mitarbeiter auswählen':null:null);return TextFormField(controller:c[f.key],keyboardType:f.number?TextInputType.number:null,minLines:f.multi?4:1,maxLines:f.multi?7:1,readOnly:f.date||f.time,onTap:f.date?()=>pickDate(f.key):f.time?()=>pickTime(f.key):null,decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder(),filled:true,fillColor:Colors.white,suffixIcon:f.date?const Icon(Icons.calendar_month):f.time?const Icon(Icons.access_time):null),validator:f.required?(v)=>v==null||v.trim().isEmpty?'Pflichtfeld':null:null);}
@override Widget build(BuildContext context)=>AlertDialog(title:Row(children:[Icon(icon(widget.kind),color:kGreen),const SizedBox(width:10),Expanded(child:Text('${widget.item==null?'Neu':'Bearbeiten'}: ${title(widget.kind)}'))]),content:SizedBox(width:560,child:loading?const SizedBox(height:160,child:Center(child:CircularProgressIndicator(color:kGreen))):Form(key:form,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:defs.map((f)=>Padding(padding:const EdgeInsets.only(bottom:11),child:field(f))).toList())))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Abbrechen')),FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:kGreen),onPressed:(){if(form.currentState!.validate())Navigator.pop(context,{for(final e in c.entries)e.key:e.value.trim()});},icon:const Icon(Icons.save),label:const Text('Speichern'))]);
Future<void>pickDate(String key)async{final d=await showDatePicker(context:context,firstDate:DateTime(2020),lastDate:DateTime(2035),initialDate:DateTime.tryParse(c[key]!.text)??DateTime.now());if(d!=null)c[key]!.text=_fmtDate(d);}
Future<void>pickTime(String key)async{final p=c[key]!.text.split(':');final t=await showTimePicker(context:context,initialTime:TimeOfDay(hour:int.tryParse(p.first)??8,minute:p.length>1?int.tryParse(p[1])??0:0));if(t!=null)c[key]!.text='${t.hour.toString().padLeft(2,'0')}:${t.minute.toString().padLeft(2,'0')}';}
}
class Def{final String key,label;final bool required,number,multi,date,time;final String? initial;const Def(this.key,this.label,{this.required=false,this.number=false,this.multi=false,this.date=false,this.time=false,this.initial});}

class CalendarView extends StatefulWidget{const CalendarView({super.key});@override State<CalendarView> createState()=>_CalendarState();}
class _CalendarState extends State<CalendarView>{DateTime month=DateTime(DateTime.now().year,DateTime.now().month);@override Widget build(BuildContext context){final first=DateTime(month.year,month.month,1);final days=DateTime(month.year,month.month+1,0).day;final off=(first.weekday+6)%7;final cells=((off+days+6)~/7)*7;const names=['Mo','Di','Mi','Do','Fr','Sa','So'];return Padding(padding:const EdgeInsets.all(28),child:Column(children:[Row(children:[const Icon(Icons.calendar_month,color:kGreen,size:31),const SizedBox(width:10),const Expanded(child:Text('Kalender',style:TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:kDarkGreen))),IconButton(onPressed:()=>setState(()=>month=DateTime(month.year,month.month-1)),icon:const Icon(Icons.chevron_left)),Text('${month.month.toString().padLeft(2,'0')}/${month.year}',style:const TextStyle(fontWeight:FontWeight.w700)),IconButton(onPressed:()=>setState(()=>month=DateTime(month.year,month.month+1)),icon:const Icon(Icons.chevron_right))]),const SizedBox(height:16),Expanded(child:Card(child:GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:7,crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:1.35),itemCount:cells+7,itemBuilder:(_,i){if(i<7)return Center(child:Text(names[i],style:const TextStyle(fontWeight:FontWeight.w700,color:kGreen)));final n=i-7-off;if(n<0||n>=days)return const SizedBox();final d=DateTime(month.year,month.month,n+1);final now=DateTime.now();final today=d.year==now.year&&d.month==now.month&&d.day==now.day;return Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:today?kPaleGreen:Colors.white,border:Border.all(color:today?kGreen:Colors.black12),borderRadius:BorderRadius.circular(10)),child:Text('${d.day}',style:TextStyle(fontWeight:FontWeight.w700,color:today?kDarkGreen:null)));})))]);}}
class Watermark extends StatelessWidget{const Watermark({super.key});@override Widget build(BuildContext context)=>const IgnorePointer(child:Align(alignment:Alignment.center,child:Opacity(opacity:.045,child:Icon(Icons.park,size:600,color:kGreen))));}
String _id()=>DateTime.now().microsecondsSinceEpoch.toString();Value<String?> _st(String? s)=>Value((s??'').isEmpty?null:s);Value<int?> _it(String? s)=>Value(int.tryParse(s??''));String?_null(String?s){final v=(s??'').trim();return v.isEmpty?null:v;}double _num(String?s)=>double.tryParse((s??'0').replaceAll(',','.'))??0;double?_dbl(String?s){final v=(s??'').replaceAll(',','.').trim();return v.isEmpty?null:double.tryParse(v);}DateTime _date(String s)=>DateTime.tryParse(s)??DateTime.now();DateTime _dt(String d,String t){final x=_date(d),p=t.split(':');return DateTime(x.year,x.month,x.day,int.tryParse(p.first)??8,p.length>1?int.tryParse(p[1])??0:0);}String _fmtDate(DateTime d)=>'${d.year.toString().padLeft(4,'0')}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';String _fmtTime(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';
