import 'package:drift/drift.dart' show Value;
import 'package:flutter/material.dart';
import 'core/database/app_database.dart';

const green = Color(0xFF2E7D32);
const darkGreen = Color(0xFF1B5E20);
const paleGreen = Color(0xFFE8F5E9);
const bg = Color(0xFFF5F8F4);

enum Mod { dashboard, sites, customers, orders, employees, time, calendar }
String modName(Mod m) { switch (m) { case Mod.dashboard:return 'Dashboard'; case Mod.sites:return 'Baustellen'; case Mod.customers:return 'Kunden'; case Mod.orders:return 'Aufträge'; case Mod.employees:return 'Mitarbeiter'; case Mod.time:return 'Zeiterfassung'; case Mod.calendar:return 'Kalender'; } }
IconData modIcon(Mod m) { switch (m) { case Mod.dashboard:return Icons.dashboard_outlined; case Mod.sites:return Icons.location_on_outlined; case Mod.customers:return Icons.people_outline; case Mod.orders:return Icons.assignment_outlined; case Mod.employees:return Icons.groups_outlined; case Mod.time:return Icons.schedule_outlined; case Mod.calendar:return Icons.calendar_month_outlined; } }

class PincusApp extends StatefulWidget { const PincusApp({super.key}); @override State<PincusApp> createState()=>_PincusAppState(); }
class _PincusAppState extends State<PincusApp> {
  final db=AppDatabase(); Mod current=Mod.dashboard;
  @override void dispose(){db.close();super.dispose();}
  @override Widget build(BuildContext context){
    final mobile=MediaQuery.sizeOf(context).width<800;
    return Scaffold(backgroundColor:bg,appBar:AppBar(backgroundColor:green,foregroundColor:Colors.white,title:Row(children:[const Icon(Icons.park_outlined),const SizedBox(width:10),Text(modName(current),style:const TextStyle(fontWeight:FontWeight.w700))]),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none))]),
      body:Row(children:[if(!mobile)Sidebar(current:current,onTap:(m)=>setState(()=>current=m)),Expanded(child:body())]),
      bottomNavigationBar:mobile?NavigationBar(selectedIndex:current==Mod.sites?1:current==Mod.customers?2:current==Mod.time?3:0,onDestinationSelected:(i)=>setState(()=>current=i==1?Mod.sites:i==2?Mod.customers:i==3?Mod.time:Mod.dashboard),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Start'),NavigationDestination(icon:Icon(Icons.location_on_outlined),label:'Baustellen'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Kunden'),NavigationDestination(icon:Icon(Icons.schedule_outlined),label:'Zeit')]):null);
  }
  Widget body(){if(current==Mod.dashboard)return Dashboard(db:db,open:(m)=>setState(()=>current=m));if(current==Mod.calendar)return CalendarPage(db:db);return ModulePage(db:db,module:current);}
}

class Sidebar extends StatelessWidget { final Mod current; final ValueChanged<Mod> onTap; const Sidebar({super.key,required this.current,required this.onTap}); @override Widget build(BuildContext context){return Container(width:118,color:Colors.white,child:Column(children:[Padding(padding:const EdgeInsets.all(9),child:Image.asset('assets/images/logo.png',height:54,errorBuilder:(_,__,___)=>const Icon(Icons.park,color:green,size:42))),Expanded(child:ListView(children:Mod.values.map((m)=>InkWell(onTap:()=>onTap(m),child:Container(margin:const EdgeInsets.symmetric(horizontal:6,vertical:2),padding:const EdgeInsets.symmetric(vertical:8),decoration:BoxDecoration(color:current==m?paleGreen:Colors.transparent,borderRadius:BorderRadius.circular(14)),child:Column(children:[Icon(modIcon(m),size:26,color:current==m?green:Colors.black54),const SizedBox(height:3),Text(modName(m),textAlign:TextAlign.center,style:TextStyle(fontSize:11.5,fontWeight:current==m?FontWeight.w700:FontWeight.w500))])))).toList()))]));} }

class Dashboard extends StatelessWidget { final AppDatabase db; final ValueChanged<Mod> open; const Dashboard({super.key,required this.db,required this.open}); Future<List<int>> counts()async=>[await db.select(db.sites).get().then((x)=>x.length),await db.select(db.customers).get().then((x)=>x.length),await db.select(db.orders).get().then((x)=>x.length),await db.select(db.employees).get().then((x)=>x.length)]; @override Widget build(BuildContext context)=>FutureBuilder<List<int>>(future:counts(),builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator(color:green));final c=s.data!;return ListView(padding:const EdgeInsets.fromLTRB(30,42,30,50),children:[const Text('Pincus Baum und Landschaftspflege',style:TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:darkGreen)),const SizedBox(height:4),const Text('Baustellenmanagement & Unternehmensverwaltung',style:TextStyle(fontSize:17,color:Colors.black54)),const SizedBox(height:28),Wrap(spacing:14,runSpacing:14,children:[Stat('Baustellen',c[0],Icons.location_on,()=>open(Mod.sites)),Stat('Kunden',c[1],Icons.people,()=>open(Mod.customers)),Stat('Aufträge',c[2],Icons.assignment,()=>open(Mod.orders)),Stat('Mitarbeiter',c[3],Icons.groups,()=>open(Mod.employees))]),const SizedBox(height:24),Card(child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[const Icon(Icons.account_tree_outlined,color:green,size:30),const SizedBox(width:14),const Expanded(child:Text('Kunde → Baustelle → Auftrag → Mitarbeiter → Arbeitszeit',style:TextStyle(fontWeight:FontWeight.w600))),FilledButton(onPressed:()=>open(Mod.orders),child:const Text('Auftrag anlegen'))]))]);}); }
class Stat extends StatelessWidget { final String label;final int value;final IconData icon;final VoidCallback tap;const Stat(this.label,this.value,this.icon,this.tap,{super.key});@override Widget build(BuildContext context)=>SizedBox(width:300,child:Card(child:InkWell(onTap:tap,borderRadius:BorderRadius.circular(14),child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:paleGreen,borderRadius:BorderRadius.circular(14)),child:Icon(icon,color:green)),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(fontWeight:FontWeight.w700)),Text('$value',style:const TextStyle(fontSize:27,fontWeight:FontWeight.w800,color:darkGreen)),const Text('Im System',style:TextStyle(color:Colors.black54))])),const Icon(Icons.chevron_right,color:Colors.black26)])))));}

enum Kind { sites, customers, orders, employees, time }
Kind kind(Mod m){switch(m){case Mod.sites:return Kind.sites;case Mod.customers:return Kind.customers;case Mod.orders:return Kind.orders;case Mod.employees:return Kind.employees;case Mod.time:return Kind.time;default:return Kind.sites;}}

class ModulePage extends StatefulWidget { final AppDatabase db;final Mod module;const ModulePage({super.key,required this.db,required this.module});@override State<ModulePage> createState()=>_ModulePageState();}
class _ModulePageState extends State<ModulePage>{late Future<List<dynamic>> data;String search='';@override void initState(){super.initState();reload();}void reload(){data=query();}Future<List<dynamic>> query(){switch(kind(widget.module)){case Kind.sites:return widget.db.select(widget.db.sites).get();case Kind.customers:return widget.db.select(widget.db.customers).get();case Kind.orders:return widget.db.select(widget.db.orders).get();case Kind.employees:return widget.db.select(widget.db.employees).get();case Kind.time:return widget.db.select(widget.db.timeEntries).get();}}String name(dynamic x){switch(kind(widget.module)){case Kind.sites:return x.title;case Kind.customers:return x.name;case Kind.orders:return x.title;case Kind.employees:return x.name;case Kind.time:return x.employeeName;}}String info(dynamic x){switch(kind(widget.module)){case Kind.sites:return x.address;case Kind.customers:return '${x.contact} • ${x.phone}';case Kind.orders:return '${x.status} • ${x.date} • ${x.price.toStringAsFixed(2)} €';case Kind.employees:return '${x.role} • ${x.targetHours} h/Woche';case Kind.time:return '${fmt(x.date)} • ${fmtTime(x.startTime)}${x.endTime==null?'':' – ${fmtTime(x.endTime)}'}';}}
@override Widget build(BuildContext context)=>FutureBuilder<List<dynamic>>(future:data,builder:(_,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator(color:green));if(s.hasError)return Center(child:Text('Fehler: ${s.error}'));final items=(s.data??[]).where((x)=>'${name(x)} ${info(x)}'.toLowerCase().contains(search.toLowerCase())).toList();return ListView(padding:const EdgeInsets.fromLTRB(30,26,30,40),children:[Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:paleGreen,borderRadius:BorderRadius.circular(14)),child:Icon(modIcon(widget.module),color:green)),const SizedBox(width:14),Expanded(child:Text(modName(widget.module),style:const TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:darkGreen))),FilledButton.icon(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Neu'))]),const SizedBox(height:18),TextField(onChanged:(v)=>setState(()=>search=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'${modName(widget.module)} durchsuchen …',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none))),const SizedBox(height:12),Text('${items.length} Einträge',style:const TextStyle(fontWeight:FontWeight.w700,color:darkGreen)),const SizedBox(height:8),...items.map((x)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:paleGreen,child:Icon(modIcon(widget.module),color:green)),title:Text(name(x),style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(info(x)),trailing:Wrap(children:[IconButton(onPressed:()=>edit(x),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>remove(x),icon:const Icon(Icons.delete_outline))]))))]);});
Future<void> edit([dynamic item])async{final v=await showDialog<Map<String,String>>(context:context,builder:(_)=>EntryDialog(db:widget.db,kind:kind(widget.module),item:item));if(v==null)return;try{if(item==null)await insert(v);else await update(item,v);setState(reload);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Speichern fehlgeschlagen: $e')));}}
Future<void> remove(dynamic x)async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Eintrag löschen?'),content:Text(name(x)),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Abbrechen')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Löschen'))]));if(ok!=true)return;switch(kind(widget.module)){case Kind.sites:await(widget.db.delete(widget.db.sites)..where((t)=>t.id.equals(x.id))).go();case Kind.customers:await(widget.db.delete(widget.db.customers)..where((t)=>t.id.equals(x.id))).go();case Kind.orders:await(widget.db.delete(widget.db.orders)..where((t)=>t.id.equals(x.id))).go();case Kind.employees:await(widget.db.delete(widget.db.employees)..where((t)=>t.id.equals(x.id))).go();case Kind.time:await(widget.db.delete(widget.db.timeEntries)..where((t)=>t.id.equals(x.id))).go();}setState(reload);}
Future<void> insert(Map<String,String>v)async{switch(kind(widget.module)){case Kind.sites:await widget.db.into(widget.db.sites).insert(SitesCompanion.insert(title:v['title']!,address:v['address']!,customerId:Value(_str(v['customerId']))));case Kind.customers:await widget.db.into(widget.db.customers).insert(CustomersCompanion.insert(id:_id(),name:v['name']!,contact:Value(v['contact']??''),phone:Value(v['phone']??''),address:Value(v['address']??'')));case Kind.orders:await widget.db.into(widget.db.orders).insert(OrdersCompanion.insert(id:_id(),title:v['title']!,customerId:Value(_str(v['customerId'])),siteId:Value(_int(v['siteId'])),status:Value(v['status']??'Neu'),date:v['date']!,price:Value(_num(v['price']))));case Kind.employees:await widget.db.into(widget.db.employees).insert(EmployeesCompanion.insert(id:_id(),name:v['name']!,role:v['role']!,targetHours:Value(_num(v['targetHours']))));case Kind.time:await widget.db.into(widget.db.timeEntries).insert(TimeEntriesCompanion.insert(siteId:int.parse(v['siteId']!),employeeName:v['employeeName']!,date:_date(v['date']!),startTime:_dt(v['date']!,v['startTime']!),endTime:Value((v['endTime']??'').isEmpty?null:_dt(v['date']!,v['endTime']!)),breakMinutes:Value(_num(v['breakMinutes'])),notes:Value(_str(v['notes']))));}}
Future<void> update(dynamic x,Map<String,String>v)async{switch(kind(widget.module)){case Kind.sites:await(widget.db.update(widget.db.sites)..where((t)=>t.id.equals(x.id))).write(SitesCompanion(title:Value(v['title']!),address:Value(v['address']!),customerId:Value(_str(v['customerId']))));case Kind.customers:await(widget.db.update(widget.db.customers)..where((t)=>t.id.equals(x.id))).write(CustomersCompanion(name:Value(v['name']!),contact:Value(v['contact']??''),phone:Value(v['phone']??''),address:Value(v['address']??'')));case Kind.orders:await(widget.db.update(widget.db.orders)..where((t)=>t.id.equals(x.id))).write(OrdersCompanion(title:Value(v['title']!),customerId:Value(_str(v['customerId'])),siteId:Value(_int(v['siteId'])),status:Value(v['status']??'Neu'),date:Value(v['date']!),price:Value(_num(v['price']))));case Kind.employees:await(widget.db.update(widget.db.employees)..where((t)=>t.id.equals(x.id))).write(EmployeesCompanion(name:Value(v['name']!),role:Value(v['role']!),targetHours:Value(_num(v['targetHours']))));case Kind.time:await(widget.db.update(widget.db.timeEntries)..where((t)=>t.id.equals(x.id))).write(TimeEntriesCompanion(siteId:Value(int.parse(v['siteId']!)),employeeName:Value(v['employeeName']!),date:Value(_date(v['date']!)),startTime:Value(_dt(v['date']!,v['startTime']!)),endTime:Value((v['endTime']??'').isEmpty?null:_dt(v['date']!,v['endTime']!)),breakMinutes:Value(_num(v['breakMinutes'])),notes:Value(_str(v['notes']))));}}
}

class EntryDialog extends StatefulWidget{final AppDatabase db;final Kind kind;final dynamic item;const EntryDialog({super.key,required this.db,required this.kind,this.item});@override State<EntryDialog> createState()=>_EntryDialogState();}
class _EntryDialogState extends State<EntryDialog>{final Map<String,TextEditingController> c={};List<dynamic> customers=[],sites=[],employees=[];String? customerId,siteId,employeeName;bool loading=true;
@override void initState(){super.initState();load();}
Future<void> load()async{customers=await widget.db.select(widget.db.customers).get();sites=await widget.db.select(widget.db.sites).get();employees=await widget.db.select(widget.db.employees).get();final x=widget.item;if(x!=null){if(widget.kind==Kind.sites||widget.kind==Kind.orders)customerId=x.customerId;if(widget.kind==Kind.orders||widget.kind==Kind.time)siteId=x.siteId?.toString();if(widget.kind==Kind.time)employeeName=x.employeeName;}if(mounted)setState(()=>loading=false);}
TextEditingController f(String k,[String?v])=>c.putIfAbsent(k,()=>TextEditingController(text:v??''));
void seed(){final x=widget.item;if(x==null||c.isNotEmpty)return;switch(widget.kind){case Kind.sites:f('title',x.title);f('address',x.address);case Kind.customers:f('name',x.name);f('contact',x.contact);f('phone',x.phone);f('address',x.address);case Kind.orders:f('title',x.title);f('status',x.status);f('date',x.date);f('price',x.price.toString());case Kind.employees:f('name',x.name);f('role',x.role);f('targetHours',x.targetHours.toString());case Kind.time:f('date',fmt(x.date));f('startTime',fmtTime(x.startTime));f('endTime',fmtTime(x.endTime));f('breakMinutes',x.breakMinutes.toString());f('notes',x.notes??'');}}
@override Widget build(BuildContext context){if(loading)return const AlertDialog(content:SizedBox(height:70,child:Center(child:CircularProgressIndicator(color:green))));seed();return AlertDialog(title:Text('${widget.item==null?'Neu':'Bearbeiten'} – ${kindName(widget.kind)}'),content:SizedBox(width:560,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:fields()))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Abbrechen')),FilledButton(onPressed:()=>Navigator.pop(context,{for(final e in c.entries)e.key:e.value.text,'customerId':customerId??'','siteId':siteId??'','employeeName':employeeName??''}),child:const Text('Speichern'))]);}
List<Widget> fields(){switch(widget.kind){case Kind.sites:return [t('title','Baustellenname'),t('address','Adresse'),customer()];case Kind.customers:return [t('name','Name / Firma'),t('contact','Ansprechpartner'),t('phone','Telefon'),t('address','Adresse')];case Kind.orders:return [t('title','Auftragsbezeichnung'),customer(),site(true),drop('status',['Neu','Angebot','Beauftragt','In Arbeit','Abgeschlossen']),t('date','Termin'),t('price','Preis (€)')];case Kind.employees:return [t('name','Name'),t('role','Rolle / Tätigkeit'),t('targetHours','Wochenstunden')];case Kind.time:return [site(false),employee(),t('date','Datum (TT.MM.JJJJ)'),t('startTime','Beginn (HH:MM)'),t('endTime','Ende (HH:MM)'),t('breakMinutes','Pause (Minuten)'),t('notes','Notizen',3)];}}
Widget t(String k,String l,[int lines=1])=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:f(k),maxLines:lines,decoration:InputDecoration(labelText:l,filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(10),borderSide:BorderSide.none))));
Widget drop(String k,List<String>v){final cur=c[k]?.text;return Padding(padding:const EdgeInsets.only(bottom:10),child:DropdownButtonFormField<String>(initialValue:v.contains(cur)?cur:v.first,decoration:InputDecoration(labelText:k,filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(10),borderSide:BorderSide.none)),items:v.map((x)=>DropdownMenuItem<String>(value:x,child:Text(x))).toList(),onChanged:(x){if(x!=null)f(k).text=x;}));}
Widget customer()=>Padding(padding:const EdgeInsets.only(bottom:10),child:DropdownButtonFormField<String?>(initialValue:customers.any((x)=>x.id==customerId)?customerId:null,decoration:InputDecoration(labelText:'Kunde',filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(10),borderSide:BorderSide.none)),items:[const DropdownMenuItem<String?>(value:null,child:Text('Kein Kunde')),...customers.map((x)=>DropdownMenuItem<String?>(value:x.id,child:Text(x.name)))],onChanged:(x)=>customerId=x));
Widget site(bool optional)=>Padding(padding:const EdgeInsets.only(bottom:10),child:DropdownButtonFormField<String?>(initialValue:sites.any((x)=>x.id.toString()==siteId)?siteId:null,decoration:InputDecoration(labelText:optional?'Baustelle (optional)':'Baustelle',filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(10),borderSide:BorderSide.none)),items:[if(optional)const DropdownMenuItem<String?>(value:null,child:Text('Keine Baustelle')),...sites.map((x)=>DropdownMenuItem<String?>(value:x.id.toString(),child:Text(x.title)))],onChanged:(x)=>siteId=x));
Widget employee()=>Padding(padding:const EdgeInsets.only(bottom:10),child:DropdownButtonFormField<String>(initialValue:employees.any((x)=>x.name==employeeName)?employeeName:null,decoration:InputDecoration(labelText:'Mitarbeiter',filled:true,fillColor:bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(10),borderSide:BorderSide.none)),items:employees.map((x)=>DropdownMenuItem<String>(value:x.name,child:Text(x.name))).toList(),onChanged:(x)=>employeeName=x));
@override void dispose(){for(final x in c.values)x.dispose();super.dispose();}}
String kindName(Kind k){switch(k){case Kind.sites:return'Baustellen';case Kind.customers:return'Kunden';case Kind.orders:return'Aufträge';case Kind.employees:return'Mitarbeiter';case Kind.time:return'Zeiterfassung';}}
class CalendarPage extends StatefulWidget{final AppDatabase db;const CalendarPage({super.key,required this.db});@override State<CalendarPage> createState()=>_CalendarPageState();}
class _CalendarPageState extends State<CalendarPage>{DateTime month=DateTime(DateTime.now().year,DateTime.now().month);@override Widget build(BuildContext context){final first=DateTime(month.year,month.month,1);final days=DateTime(month.year,month.month+1,0).day;final offset=(first.weekday+6)%7;final cells=((offset+days+6)~/7)*7;const names=['Mo','Di','Mi','Do','Fr','Sa','So'];return Padding(padding:const EdgeInsets.all(28),child:Column(children:[Row(children:[const Icon(Icons.calendar_month,color:green,size:31),const SizedBox(width:10),const Expanded(child:Text('Kalender',style:TextStyle(fontSize:29,fontWeight:FontWeight.w700,color:darkGreen))),IconButton(onPressed:()=>setState(()=>month=DateTime(month.year,month.month-1)),icon:const Icon(Icons.chevron_left)),Text('${month.month.toString().padLeft(2,'0')}/${month.year}',style:const TextStyle(fontWeight:FontWeight.w700)),IconButton(onPressed:()=>setState(()=>month=DateTime(month.year,month.month+1)),icon:const Icon(Icons.chevron_right))]),const SizedBox(height:16),Expanded(child:Card(child:GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:7,crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:1.35),itemCount:cells+7,itemBuilder:(_,i){if(i<7)return Center(child:Text(names[i],style:const TextStyle(fontWeight:FontWeight.w700,color:green)));final n=i-7-offset;if(n<0||n>=days)return const SizedBox();final d=DateTime(month.year,month.month,n+1);final now=DateTime.now();final today=d.year==now.year&&d.month==now.month&&d.day==now.day;return Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:today?paleGreen:Colors.white,border:Border.all(color:today?green:Colors.black12),borderRadius:BorderRadius.circular(10)),child:Text('${d.day}',style:TextStyle(fontWeight:FontWeight.w700,color:today?darkGreen:null)));})))]);}}
String _id()=>DateTime.now().microsecondsSinceEpoch.toString();String? _str(String?v)=>v==null||v.trim().isEmpty?null:v.trim();int? _int(String?v)=>v==null||v.trim().isEmpty?null:int.tryParse(v);double _num(String?v)=>double.tryParse((v??'').replaceAll(',','.'))??0;DateTime _date(String v){final p=v.trim().split(RegExp(r'[.\-/]'));if(p.length==3){if(p[0].length==4)return DateTime(int.parse(p[0]),int.parse(p[1]),int.parse(p[2]));return DateTime(int.parse(p[2]),int.parse(p[1]),int.parse(p[0]));}return DateTime.now();}DateTime _dt(String d,String t){final x=_date(d);final p=t.split(':');return DateTime(x.year,x.month,x.day,int.tryParse(p[0])??0,p.length>1?int.tryParse(p[1])??0:0);}String fmt(DateTime? d)=>d==null?'':'${d.day.toString().padLeft(2,'0')}.${d.month.toString().padLeft(2,'0')}.${d.year}';String fmtTime(DateTime? d)=>d==null?'':'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';
